version: '3'

services:
  redis:
    image: redis
    volumes:
     - "./redis.conf:/usr/local/etc/redis/redis.conf"
    restart: always
  guerrilla:
    image: bfritscher/go-guerrilla
    ports:
      - "25:25"
    volumes:
     - "./goguerrilla.conf:/go/src/app/goguerrilla.conf"
    depends_on:
      - redis
    restart: always
  node:
    build: .
    env_file: .env
    command: npm run start
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "8888:80"
    depends_on:
      - redis
