version: '3'

services:
  redis:
    image: redis
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
     - "./redis.conf:/usr/local/etc/redis/redis.conf"
    restart: always
  guerrilla:
    image: bfritscher/go-guerrilla
    ports:
      - "25:25"
    volumes:
     - "./goguerrilla.conf:/go/src/app/goguerrilla.conf"
    depends_on:
      - redis
    restart: always
  node:
    image: bfritscher/pdfui-backend
    env_file: .env
    command: npm run start
    restart: always
    ports:
      - "127.0.0.1:8081:80"
    depends_on:
      - redis
      - guerrilla
